### ISSUE TITLE
РГР

### ISSUE THREAD

**Issue by sokolnikovalexey** [BlackFox101/LwPascal#12]
Непонятно, зачем использовали разделение алфавитов на языки, если потом все равно использовали совместно 
  RusAlphabet = ['�' .. '�', '�', '�' .. '�', '�'];
  EngAlphabet = ['A' .. 'Z', 'a' .. 'z'];
  UpperCase = ['�' .. '�', '�', 'A' .. 'Z'];

**Comment by BlackFox101** [comment]
Исправил

**Comment by sokolnikovalexey** [comment]
Модуль WordModule не собирается, неизвестные переменные:
IF (Letter IN RusAlphabet) OR (Letter IN EngAlphabet)

Будьте внимательнее, в следующий раз, при подобных замечаниях буду ставить коэф-ты

**Comment by sokolnikovalexey** [comment]
Вы используете метод dispose при печати дерева и получается, что метод печати не только выводит дерево, но и чистит его. Лучше разбить на 2 метода, каждый из которых выполняет работу свою без неожиданностей

**Comment by BlackFox101** [comment]
Исправил
